# Generated by Django 4.2.16 on 2025-01-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryquest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='city',
            field=models.CharField(default='', max_length=240, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='phone',
            field=models.CharField(default='', max_length=14, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='zip',
            field=models.CharField(default='', max_length=5, verbose_name='Zip'),
            preserve_default=False,
        ),
    ]
