# Generated by Django 4.2.16 on 2024-09-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryquest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('membership_zone', models.ManyToManyField(to='libraryquest_app.membershipzone')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='membership_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='libraryquest_app.membershipzone'),
        ),
    ]
